### ISSUE TITLE
Potential shortcut for Dijkstra implementation?

### ISSUE THREAD

**Issue by jogru0** [evenfurther/pathfinding#476]
Hi!

I see that for A*, we have a shortcut to not go through the neighbors of a node that was visited before already: https://github.com/evenfurther/pathfinding/commit/3cde90796c0c5416dd4a56013e0ddeb2823af7ba

I was wondering, why don't we do a similar check for Dijkstra?

**Comment by samueltardieu** [comment]
The shortcut has been removed in 808b951c5a9eb5dd25adbd46a5887525d0a0913d as it gave worst execution times. You may try to reintroduce it and tweak it so that it gets better performance if you wish.
