### ISSUE TITLE
Second argument to dijkstra raises an type error

### ISSUE THREAD

**Issue by kwiat1990** [evenfurther/pathfinding#488]
Hi, I‘m testing currently Dijkstra algorithm on a `Matrix` of i32. Sadly I realized that calling `neighbors` on the matrix yields points of type `(usize, usize)`, which can’t be used directly in `dijkstra` function as it expect a tuple containing a point and its value. So I thought that it could be done by combining `neighbors` and `items`, which yields an iterator on elements of type `((usize, usize), &i32)`.

For some reason I get an type error as second argument of the dijkstra function expects a rather odd type `(((usize, usize), i32), C)`.  Looking at function’s signature C should then equal to i32, but overall the right type should be `((usize, usize), i32)`.  To be honest I don’t quite know why I get this error because what I’m doing it’s pretty similar to the example from docs.

I would appreciate any feedback and hints on how I could fix it.

**Comment by samueltardieu** [comment]
Hi Mateusz. If your moves have a fixed (1) cost, you should use `dfs` instead of `dijkstra`, in which case you can use the result of `Matrix::neighbours()` directly. However, if you want to use `dijkstra`, you have to add the cost indeed in addition to each neighbour.

If your node type is `(usize, usize)` and your cost is `i32`, your `neighbours` function will take a `&(usize, usize)` (the node) and return an iterator of `((usize, usize), i32)` (its neighbours and their associated cost).

[Here](https://gist.github.com/samueltardieu/814874f2365ea38a514ecb8e9838745e) is a more complicated example from today's [advent of code](https://adventofcode.com/2023/day/17) problem. You will see that the type of the node is much more complicated since it must represent more than just a position, it also contains a direction and a number of steps performed in this direction: `((usize, usize), (isize, isize), usize)`. As a consequence, since in this problem each edge cost is expressed also as a `usize`, the return value from the `neighbours` function is `(((usize, usize), (isize, isize), usize), usize)`.

I hope this helps.

**Comment by kwiat1990** [comment]
Hi, thank for responding. I’m also using `pathfinding` crate to solve this puzzle, so I won’t look at your solution. For starters I wanted to get it working for the example input grid without any additional data but coordinates and weight. 

I’m a bit confused because in the first [official example](https://docs.rs/pathfinding/4.6.0/pathfinding/directed/dijkstra/fn.dijkstra.html) one pass in a collected vector instead of an iterator to the second parameter whereas in the next example example an iterator. So both are correct although function signature expects an iterator?

The next big question for me is why I get the mentioned error:
```
I throws following error: type mismatch resolving `<impl Iterator<Item = ((usize, usize), &i32)> as IntoIterator>::Item == (((usize, usize), &i32), _)` [E0271] expected `(((usize, usize), &i32), _)`, found `((usize, usize), &i32)` Note: expected tuple `(((usize, usize), &i32), _)` found tuple `((usize, usize), &i32)` Note: required by a bound in `pathfinding::prelude::dijkstra`
```
 I have a rather simple code:
```rs
let grid = Matrix::from_rows(
        input
            .lines()
            .map(|line| line.chars().map(|c| c.to_digit(10).unwrap() as i32)),
    )
    .unwrap();

    let mut items = grid.items();
    let start = items.next().unwrap();
    let goal = items.last().unwrap();

    println!(
        "{:?}",
        dijkstra( // here it throws the error
            &start,
            |p| neighbours(&grid, p.0).into_iter(),
            |p| p.0 == goal.0
        )
    );

// ——————

fn neighbours(
    matrix: &Matrix<i32>,
    point: (usize, usize),
) -> impl Iterator<Item = ((usize, usize), &i32)> {
    //) -> Vec<((usize, usize), &i32)> {
    let neighbours: Vec<(usize, usize)> = matrix.neighbours(point, false).collect();
    matrix.items().filter(move |(x, _)| neighbours.contains(x))
    //.collect()
}
```

From my understanding the custom `neighbours` function fills `dijkstra`’s signature as it returns an iterator over `((usize, usize), &i32)` and in other words `impl Iterator<Item=(N, C)>`. I did also try calling `.into_iter()` but without any difference. Obviously I’m missing something but I don’t quite know what exactly?

**Comment by samueltardieu** [comment]
> I’m a bit confused because in the first [official example](https://docs.rs/pathfinding/4.6.0/pathfinding/directed/dijkstra/fn.dijkstra.html) one pass in a collected vector instead of an iterator to the second parameter whereas in the next example example an iterator. So both are correct although function signature expects an iterator?

The function signature doesn't expect `Iterator`, it expects [`IntoIterator`](https://doc.rust-lang.org/nightly/std/iter/trait.IntoIterator.html), which covers every type that can be converted into an `Iterator`. This covers both `Iterator` instances or types such as `Vec`, arrays, slices, etc.

> The next big question for me is why I get the mentioned error:

The first argument you give do `dijkstra()` is `&start`, with `start` being of type `((usize, usize), &i32)`. The compiler deduces that this is the type of the nodes. So the neighbours + the edge weight must be a couple with this type and the cost type (`C`), so it expects (rightly) a `(((usize, usize), &i32), C)`.

**Comment by kwiat1990** [comment]
Ah, I didn’t thought about that in this way. So to clarify things a little bit:
1. Matrix consists of nodes, which holds a tuple with coordinates and the cost -> `((usize, usize), &i32)`.
2. In `dijkstra` as starting point I should pass in only coordinates and not the whole node -> `node.0 == (usize, usize)`;
3. In the function passed in to the second argument I should map points with its cost.

After changing the code to follow above requirements, it compiles and seems to run correctly.
