### ISSUE TITLE
All the links in Algorithms in Readme are broken

### ISSUE THREAD

**Issue by simonsan** [evenfurther/pathfinding#534]
All of these links are broken:
![2024-02-11 18_06_27-evenfurther_pathfinding_ Pathfinding library for rust — Mozilla Firefox](https://github.com/evenfurther/pathfinding/assets/14062932/71d9563c-64b7-4980-b531-e4cfe148d035)

**Comment by samueltardieu** [comment]
On what URL? They look fine on <https://docs.rs/pathfinding/latest/pathfinding/>.

**Comment by samueltardieu** [comment]
Oh, when you look at them on GitHub. I'll update this and remove the list, I'll link the generated doc instead.
