### ISSUE TITLE
Add Implementation for Prim's algorithm

### ISSUE THREAD

**Issue by jafar75** [evenfurther/pathfinding#576]
Hi there, 
It is known that Kruskal's algorithm for finding MST, has a simpler implmentation than Prim's and also is more efficient for sparse graph. 
If it is needed, I'm willing to implement prim's algorithm, as it is more suitable when the graph is dense. 
[useful link](https://www.geeksforgeeks.org/difference-between-prims-and-kruskals-algorithm-for-mst/)

**Comment by samueltardieu** [comment]
Hi @jafar75. If you have any use for it, please do, I'd be happy to integrate it.

**Comment by jafar75** [comment]
@samueltardieu I managed to provide an implementation for this algorithm. I thought, it's better to provide an exactly similar function api with Kruskal algorithm. as below

`pub fn kruskal<N, C>(edges: &[(N, N, C)]) -> impl Iterator<Item = (&N, &N, C)>`

But, I have some issues to effciently impl the Prim, using the above input params. 
Can I switch to somehow _Adjacancy_ _List_ as input parameters, to provide an optimal solution?
